# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\escritorio\Proyecto_Local\Frontend\Ui\Inicio2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1385, 909)
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(249, 0))
        self.frame.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame.setStyleSheet("background-color:#1a1b1d;\n"
"border-radius: 00 ;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(17, 2, 14, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#dddcdf;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#c3c2c4; opacity:0.1;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.boton_asistencia = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.boton_asistencia.setFont(font)
        self.boton_asistencia.setStyleSheet("color:#dddcdf; \n"
"text-align:left;\n"
"margin:0;\n"
"background-color:#323435;\n"
"border-radius:10;\n"
"hover{color: white;};")
        self.boton_asistencia.setObjectName("boton_asistencia")
        self.verticalLayout_2.addWidget(self.boton_asistencia)
        self.boton_pago_diario = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.boton_pago_diario.setFont(font)
        self.boton_pago_diario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boton_pago_diario.setStyleSheet("color:#dddcdf; \n"
"text-align:left;\n"
"margin:0;\n"
"background-color:#323435;\n"
"border-radius:10;\n"
"")
        self.boton_pago_diario.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.boton_pago_diario.setObjectName("boton_pago_diario")
        self.verticalLayout_2.addWidget(self.boton_pago_diario)
        self.boton_pago_semanal = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.boton_pago_semanal.setFont(font)
        self.boton_pago_semanal.setStyleSheet("color:#dddcdf; \n"
"text-align:left;\n"
"margin:0;\n"
"background-color:#323435;\n"
"border-radius:10;\n"
"")
        self.boton_pago_semanal.setObjectName("boton_pago_semanal")
        self.verticalLayout_2.addWidget(self.boton_pago_semanal)
        self.boton_estadisticas = QtWidgets.QPushButton(self.frame)
        self.boton_estadisticas.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.boton_estadisticas.setFont(font)
        self.boton_estadisticas.setStyleSheet("color:#dddcdf; \n"
"text-align:left;\n"
"margin:0;\n"
"background-color:#323435;\n"
"border-radius:10;\n"
"")
        self.boton_estadisticas.setObjectName("boton_estadisticas")
        self.verticalLayout_2.addWidget(self.boton_estadisticas)
        self.boton_balance = QtWidgets.QPushButton(self.frame)
        self.boton_balance.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(20)
        self.boton_balance.setFont(font)
        self.boton_balance.setStyleSheet("color:#dddcdf; \n"
"text-align:left;\n"
"margin:0;\n"
"background-color:#323435;\n"
"border-radius:10;\n"
"")
        self.boton_balance.setObjectName("boton_balance")
        self.verticalLayout_2.addWidget(self.boton_balance)
        spacerItem1 = QtWidgets.QSpacerItem(20, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Administracion -  Menú"))
        self.label_4.setText(_translate("MainWindow", "Lilith"))
        self.label_3.setText(_translate("MainWindow", "Menu"))
        self.boton_asistencia.setText(_translate("MainWindow", "   Asistencia"))
        self.boton_pago_diario.setText(_translate("MainWindow", "   Pago Diario"))
        self.boton_pago_semanal.setText(_translate("MainWindow", "   Pago Semanal"))
        self.boton_estadisticas.setText(_translate("MainWindow", "   Estadisticas"))
        self.boton_balance.setText(_translate("MainWindow", "   Balance"))
        self.label_5.setText(_translate("MainWindow", "Sistema de Administracion"))
